-- SERENIA 500M knowledge backend schema (Supabase/PostgreSQL)
-- Public client should query only the RPC/Edge Function, never write knowledge directly.

create extension if not exists pg_trgm;
create extension if not exists vector;

create table if not exists public.knowledge_entries (
  id bigint generated by default as identity primary key,
  lang text not null check (lang in ('fr','en','de')),
  topic text not null,
  subtopic text,
  situation text not null,
  emotion text,
  need text,
  intensity smallint not null default 2 check (intensity between 1 and 5),
  challenge_level smallint not null default 2 check (challenge_level between 0 and 5),
  spiritual_level smallint not null default 1 check (spiritual_level between 0 and 5),
  safety_level smallint not null default 0 check (safety_level between 0 and 5),
  triggers text[] not null default '{}',
  tags text[] not null default '{}',
  response text not null,
  followup text,
  embedding vector(1536),
  created_at timestamptz not null default now()
);

create index if not exists knowledge_lang_topic_idx
  on public.knowledge_entries(lang, topic);

create index if not exists knowledge_triggers_gin
  on public.knowledge_entries using gin(triggers);

create index if not exists knowledge_tags_gin
  on public.knowledge_entries using gin(tags);

create index if not exists knowledge_response_trgm
  on public.knowledge_entries using gin(response gin_trgm_ops);

alter table public.knowledge_entries enable row level security;

drop policy if exists "knowledge_read_only" on public.knowledge_entries;
create policy "knowledge_read_only"
on public.knowledge_entries
for select
to anon, authenticated
using (true);

-- No insert/update/delete policy for anon/authenticated.

create or replace function public.search_serenia_knowledge(
  p_lang text,
  p_topics text[],
  p_terms text[],
  p_limit integer default 8
)
returns table (
  id bigint,
  lang text,
  topic text,
  subtopic text,
  situation text,
  emotion text,
  need text,
  intensity smallint,
  challenge_level smallint,
  spiritual_level smallint,
  safety_level smallint,
  response text,
  followup text,
  score integer
)
language sql
stable
security invoker
as $$
  select
    k.id,k.lang,k.topic,k.subtopic,k.situation,k.emotion,k.need,
    k.intensity,k.challenge_level,k.spiritual_level,k.safety_level,
    k.response,k.followup,
    (
      case when k.topic = any(p_topics) then 30 else 0 end
      + coalesce((select count(*) * 6 from unnest(k.triggers) t where t = any(p_terms)),0)
      + coalesce((select count(*) * 3 from unnest(k.tags) t where t = any(p_terms)),0)
    )::integer as score
  from public.knowledge_entries k
  where k.lang = p_lang
    and (k.topic = any(p_topics) or k.triggers && p_terms or k.tags && p_terms)
  order by score desc, k.id asc
  limit greatest(1,least(p_limit,20));
$$;
